---
title: "ScreenSeq Plate Report"
author: "Alex Kim"
date: "7/17/2018"
output: html_document
params:
  plate: NA
  traverse_out_fn: NA
---

```{r setup, include=FALSE}
library(ggplot2)
library(knitr)
library(kableExtra)
```

```{r data, include=FALSE}
traverse_out_fn <- params$traverse_out_fn
plate <- params$plate

createColumns <- function(row_header) {
  lapply(1:4, function(i) {
    
    barcodes <- traverse_out_fn(list(plate[[i]]), "barcode")
    bc_dt <- data.frame(matrix(unlist(strsplit(barcodes, "_")), ncol=2, byrow=T),stringsAsFactors=FALSE)
    names(bc_dt) <- c("fw", "rv")
    
    bc_dt
    
    kable(bc_dt)
  })
}
row1_header <- c("A","C","E","G")
row2_header <- c("B","D","F","H")  
```

### Barcodes

```{r}
sliderInput("bins", "Number of bins:", 30, min = 1, max = 50)

renderPlot({
  x    = faithful[, 2]  # Old Faithful Geyser data
  bins = seq(min(x), max(x), length.out = input$bins + 1)

  # draw the histogram with the specified number of bins
  hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
```

```{r}
createColumns(row2_header)
```   
    
### Target Genes

```{r}
```
